version: '3.1'

services:
  db:
    image: mariadb:10.6.8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
      MARIADB_DATABASE: abnamro
    ports:
      - "3306:3306"
