
# Local configuration

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/recipebook
    username: mariadb
    password: mariadb
  jpa:
    show-sql: true
